### ISSUE TITLE
problems when launching command

### ISSUE THREAD

**Issue by Matthieu-Vachet** [Inklay/Pokemon-TCG#2]
the bot this log on discord, all the configuration commands work, but when I want to run the command "tgc money" the bot crashes and says it as an error: 

TypeError: Cannot read property ‘client’ of undefined 
![42822B32-35D5-411A-B6BE-02144E0A753B](https://user-images.githubusercontent.com/79032023/108508344-f3394680-72bb-11eb-943d-015dffe5a3a8.png)

error cause at line 13 of file: MessageEmbed.js

Object.defineProperty(this, ‘client’, { value: message.client )

how can i fix this error?

**Comment by Inklay** [comment]
Hey, thanks for reporting this issue, I will work on it during the weekend, I'll keep you updated 😉

**Comment by Inklay** [comment]
Can you show me the content of server.json and user.json please ?

**Comment by Matthieu-Vachet** [comment]
good evening :)

yes here they are:
https://nsm09.casimages.com/img/2021/02/21//21022102133025847417273619.png
https://nsm09.casimages.com/img/2021/02/21//21022102133125847417273620.png

so the command prefix, and language works.
But the 3 other tgc commands crash the bot

ERROR:

C:\Users\MeghanC\Desktop\Pokemon-TCG-main\src
λ node app.js
app.js: Logged in as LunalaBot!
C:\Users\MeghanC\node_modules\discord.js\src\structures\MessageEmbed.js:13
    Object.defineProperty(this, 'client', { value: message.client });
                                                           ^

TypeError: Cannot read property 'client' of undefined
    at new MessageEmbed (C:\Users\MeghanC\node_modules\discord.js\src\structures\MessageEmbed.js:13:60)
    at userHandler.<instance_members_initializer> (C:\Users\MeghanC\Desktop\Pokemon-TCG-main\src\user.js:6:13)
    at new userHandler (C:\Users\MeghanC\Desktop\Pokemon-TCG-main\src\user.js:30:16)
    at Client.<anonymous> (C:\Users\MeghanC\Desktop\Pokemon-TCG-main\src\app.js:132:19)
    at Client.emit (events.js:315:20)
    at MessageCreateHandler.handle (C:\Users\MeghanC\node_modules\discord.js\src\client\websocket\packets\handlers\MessageCreate.js:9:34)
    at WebSocketPacketManager.handle (C:\Users\MeghanC\node_modules\discord.js\src\client\websocket\packets\WebSocketPacketManager.js:108:65)
    at WebSocketConnection.onPacket (C:\Users\MeghanC\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:336:35)
    at WebSocketConnection.onMessage (C:\Users\MeghanC\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:299:17)
    at WebSocket.onMessage (C:\Users\MeghanC\node_modules\ws\lib\event-target.js:120:16)

**Comment by Matthieu-Vachet** [comment]
suddenly I use the holds that I hosted on my discord and there is a bug when we buy the booster!

Even when we have more agent we can still continue to buy Xd

**Comment by Inklay** [comment]
Mmmmh that sounds like we are not using the same version of NodeJS, can you run `node -v` and send me the output please ?

**Comment by Matthieu-Vachet** [comment]
I'll send it to you at the end of the afternoon when I get home.  but everything and one day so i use the latest version of node.js, npm, and discord.js on windows

**Comment by Matthieu-Vachet** [comment]
do you have a discord so that we can talk faster?

**Comment by Inklay** [comment]
Sure, it's Inklay#5226

**Comment by Matthieu-Vachet** [comment]
Send

**Comment by Matthieu-Vachet** [comment]
the worry of command crash and settle!  thank you to you ^^
